#include "../lib/my.h"

int main()
{
  my_str(my_find("jamal", 's'));
  my_char('\n');
  my_str(my_find("jamal", 'm'));
  my_char('\n');
  my_str(my_find(NULL, 'f'));
  my_char('\n');
  my_str("This is where it may fault\n");
  my_str(my_find("", 'f'));
  my_char('\n');
  my_str(my_rfind("found", 'f'));
  my_char('\n');
  my_str(my_rfind("found", 'i'));
  my_char('\n');
  my_str(my_rfind(NULL, 'f'));
  my_str("or here\n");
  my_char('\n');
  my_str(my_rfind("", 'f'));
  my_char('\n');
  my_str(my_strcat("", ""));
  my_str("fault\n");
  my_str(my_strcat("", "that"));
  my_str("fault\n");
  my_str(my_strcat("this", ""));
  my_str("fault\n");
  my_str(my_strcat(NULL, NULL));
  my_str(my_strcat(NULL, "that"));
  my_str(my_strcat("this", NULL));
  my_str(my_strcat("this", "that"));
  my_int(my_strcmp("abc", "abcd"));
  my_char('\n');
  my_int(my_strcmp("this", NULL));
  my_char('\n');
  my_int(my_strcmp(NULL, "that"));
  my_char('\n');
  my_int(my_strcmp(NULL, NULL));
  my_char('\n');
  my_int(my_strcmp("aa", "aa"));
  my_char('\n');
  my_int(my_strcmp("b", "a"));
  my_char('\n');
  my_str("strncmp starts its test here.");
  my_char('\n');
  my_int(my_strncmp("a", "b", 1));
  my_char('\n');
  my_int(my_strncmp("b", "a", 1));
  my_char('\n');
  my_int(my_strncmp("aaaa", "aaaa", 4));
  my_char('\n');
  my_int(my_strncmp("this", NULL, 2));
  my_char('\n');
  my_int(my_strncmp(NULL, "that", 2));
  my_char('\n');
  my_int(my_strncmp(NULL, NULL, 2));
  my_char('\n');
  my_int(my_strncmp("a", "b", 0));
  my_char('\n');
  my_int(my_strncmp("", "", 2));
  my_char('\n');
  my_int(my_strncmp("this", "that", -1));
  my_char('\n');
  my_strconcat("this", "that");
  my_strconcat("this", "");
  my_strconcat("this", NULL);
  my_strconcat("", "that");
  my_strconcat(NULL, "that");
  my_strconcat("", "");
  my_strconcat(NULL, NULL);
  my_strnconcat("this", "that", 0);
  my_strnconcat("this", "that", 2);
  my_strnconcat("this", "that", 4);
  my_strnconcat("this", "that", 5);
  my_strnconcat("this", NULL, 2);
  my_strnconcat("this", "", 2);
  my_strnconcat(NULL, "that", 2);
  my_strnconcat("", "that", 2);
  my_strnconcat("", "that", 0);
  my_strnconcat("this", "that", -1);
  my_strnconcat(NULL, NULL, 2);
  my_stdstrconcat("this", "that", 0);
  my_stdstrconcat("this", "that", 2);
  my_stdstrconcat("this", "that", 4);
  my_stdstrconcat("this", "that", 5);
  my_stdstrconcat("", "", 0);
  my_stdstrconcat("this", "that", -1);
  my_stdstrconcat(NULL, NULL, 2);
  char c[]="thissssssssss";
  my_str("Test 1\n");
  my_str(my_strcpy(c, "Hello World"));
  my_str("Test 2\n");
  my_str(my_strcpy(c, ""));
  my_str("Test 3\n");
  my_str(my_strcpy(c, "darn"));
  my_str("Test 4\n");
  my_str(my_strcpy(c, NULL));
  my_str("Test 1n\n");
  my_str(my_strncpy(c, "that", -1));
  my_str("Test 2n\n");
  my_str(my_strncpy(c, "that", 0));
  my_str("Test 3n\n");
  my_str(my_strncpy(c, "that", 2));
  my_str("Test 4n\n");
  my_str(my_strncpy(c, "that", 4));
  my_str("Test 5n\n");
  my_str(my_strncpy(c, "that", 5));
  my_str(my_strdup("this"));
  my_str(my_strdup(""));
  my_str("NULL here\n");
  my_str(my_strdup(NULL));
  my_str(my_strdup("\n"));
}
